#serverAddress: 192.168.43.177
serverAddress: localhost
serverPort: 3099

DB_NAME: db_name
DB_IP: localhost
DB_PORT: 1433
DB_USERNAME: sa
DB_PASSWORD: Password

http.auth.id: id
http.auth.secret: secret

DROP: false
SEED: true